#!/bin/bash

# Agent Browser Boot Script
# Quick start guide and common commands

echo "========================================="
echo "🤖 AGENT BROWSER BOOT COMMANDS"
echo "========================================="
echo ""

# Check if agent-browser is installed
if command -v agent-browser &> /dev/null; then
    echo "✅ Agent Browser is installed!"
    agent-browser --version
else
    echo "❌ Agent Browser is not installed."
    echo ""
    echo "To install:"
    echo "  npm install -g agent-browser"
    echo "  agent-browser install  # Download Chromium"
    echo ""
    exit 1
fi

echo ""
echo "========================================="
echo "🚀 QUICK START COMMANDS"
echo "========================================="
echo ""
echo "1. Open a website:"
echo "   agent-browser open https://google.com"
echo ""
echo "2. Take snapshot (see interactive elements):"
echo "   agent-browser snapshot"
echo ""
echo "3. Click element (use ref from snapshot):"
echo "   agent-browser click @e1"
echo ""
echo "4. Fill form field:"
echo "   agent-browser fill @e2 \"test@example.com\""
echo ""
echo "5. Take screenshot:"
echo "   agent-browser screenshot page.png"
echo ""
echo "6. Close browser:"
echo "   agent-browser close"
echo ""

echo "========================================="
echo "🎯 COMMON WORKFLOWS"
echo "========================================="
echo ""
echo "A. Google Search Automation:"
echo "   agent-browser open https://google.com"
echo "   agent-browser fill \"textarea[name='q']\" \"hello world\""
echo "   agent-browser press Enter"
echo "   agent-browser screenshot results.png"
echo "   agent-browser close"
echo ""
echo "B. Form Filling:"
echo "   agent-browser open https://example.com/form"
echo "   agent-browser fill \"#name\" \"John Doe\""
echo "   agent-browser fill \"#email\" \"john@example.com\""
echo "   agent-browser click \"#submit\""
echo "   agent-browser close"
echo ""
echo "C. Page Scraping:"
echo "   agent-browser open https://example.com"
echo "   agent-browser get title"
echo "   agent-browser get text \"h1\""
echo "   agent-browser get count \"a\""
echo "   agent-browser close"
echo ""

echo "========================================="
echo "⚙️  USEFUL OPTIONS"
echo "========================================="
echo ""
echo "Run in headless mode (no UI):"
echo "  agent-browser --headless open https://google.com"
echo ""
echo "Set viewport size:"
echo "  agent-browser --viewport 1920x1080 open https://example.com"
echo ""
echo "Add delay between actions:"
echo "  agent-browser --delay 1000 open https://example.com"
echo ""
echo "Get help:"
echo "  agent-browser --help"
echo "  agent-browser open --help"
echo ""

echo "========================================="
echo "🔍 GETTING ELEMENT REFERENCES"
echo "========================================="
echo ""
echo "The 'snapshot' command is key for AI agents:"
echo ""
echo "1. First, take a snapshot:"
echo "   agent-browser snapshot"
echo ""
echo "2. You'll see output like:"
echo "   @e1: button \"Submit\" (role=button)"
echo "   @e2: input \"Email\" (role=textbox)"
echo "   @e3: link \"Learn more\" (role=link)"
echo ""
echo "3. Use these refs in commands:"
echo "   agent-browser click @e1"
echo "   agent-browser fill @e2 \"text\""
echo "   agent-browser get text @e3"
echo ""

echo "========================================="
echo "🎮 TRY IT NOW!"
echo "========================================="
echo ""
echo "Copy and paste these commands to try Agent Browser:"
echo ""
echo "# 1. Quick test (headless mode)"
echo "agent-browser --headless open https://httpbin.org/html"
echo "agent-browser get title"
echo "agent-browser screenshot test.png"
echo "agent-browser close"
echo ""
echo "# 2. Interactive example"
echo "agent-browser open https://google.com"
echo "# (Browser will open - interact manually)"
echo "# Then in another terminal:"
echo "agent-browser snapshot"
echo "agent-browser screenshot google.png"
echo "agent-browser close"
echo ""

echo "========================================="
echo "📚 LEARN MORE"
echo "========================================="
echo ""
echo "Full documentation:"
echo "  agent-browser --help"
echo ""
echo "GitHub repository:"
echo "  https://github.com/vercel-labs/agent-browser"
echo ""
echo "For AI agents, check AGENTS.md in the repo"
echo ""

echo "========================================="
echo "💡 PRO TIP"
echo "========================================="
echo ""
echo "Chain commands with && for simple scripts:"
echo ""
echo "agent-browser --headless open https://google.com \\"
echo "  && agent-browser fill \"textarea[name='q']\" \"test\" \\"
echo "  && agent-browser press Enter \\"
echo "  && agent-browser screenshot result.png \\"
echo "  && agent-browser close"
echo ""
echo "Happy automating! 🚀"