#!/bin/bash

echo "========================================="
echo "EastsideBot Cloudflare Deployment Fix"
echo "========================================="
echo ""
echo "Based on your Cloudflare dashboard URL:"
echo "https://dash.cloudflare.com/a1ede525e60bbe56f5af3960df6e34c7/workers/services/view/eastsidebot/production/metrics"
echo ""
echo "This script will help fix your eastsidebot deployment issues."
echo ""

# Step 1: Check Cloudflare authentication
echo "STEP 1: Checking Cloudflare authentication..."
echo "----------------------------------------"
if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
    echo "✅ Cloudflare API token is set in environment"
    echo "Token preview: ${CLOUDFLARE_API_TOKEN:0:10}..."
else
    echo "❌ No Cloudflare API token found in environment"
    echo ""
    echo "To fix this:"
    echo "1. Go to https://dash.cloudflare.com/profile/api-tokens"
    echo "2. Create a new token with 'Edit Cloudflare Workers' permissions"
    echo "3. Copy the token and set it:"
    echo "   export CLOUDFLARE_API_TOKEN='your-token-here'"
    echo "   # Or add to ~/.zshrc:"
    echo "   echo 'export CLOUDFLARE_API_TOKEN=\"your-token-here\"' >> ~/.zshrc"
    echo "   source ~/.zshrc"
fi

# Step 2: Check for eastsidebot project files
echo ""
echo "STEP 2: Looking for eastsidebot project files..."
echo "----------------------------------------"
EASTSIDE_FILES=$(find . -type f \( -name "*eastside*" -o -name "*east*" \) 2>/dev/null | head -10)
if [ -n "$EASTSIDE_FILES" ]; then
    echo "Found files:"
    echo "$EASTSIDE_FILES"
else
    echo "No eastsidebot files found in current directory."
    echo ""
    echo "Possible locations to check:"
    echo "1. Check if eastsidebot is in a different directory"
    echo "2. Check if it was deployed from a different machine"
    echo "3. Check Cloudflare dashboard for worker source code"
fi

# Step 3: Check current worker deployments
echo ""
echo "STEP 3: Checking current worker deployments..."
echo "----------------------------------------"
echo "To check your deployed workers, you need to:"
echo ""
echo "1. First authenticate with Cloudflare:"
echo "   npx wrangler login"
echo "   # OR set API token:"
echo "   export CLOUDFLARE_API_TOKEN='your-token'"
echo ""
echo "2. Then list deployments:"
echo "   npx wrangler deployments list"
echo ""
echo "3. Check specific worker:"
echo "   npx wrangler deployments list --name eastsidebot"
echo "   npx wrangler tail --name eastsidebot"

# Step 4: Common deployment issues and fixes
echo ""
echo "STEP 4: Common deployment issues and fixes..."
echo "----------------------------------------"
echo ""
echo "Issue 1: Worker not responding"
echo "  Fix: Check worker logs in Cloudflare dashboard"
echo "  Command: npx wrangler tail --name eastsidebot"
echo ""
echo "Issue 2: Authentication errors"
echo "  Fix: Re-authenticate or use API token"
echo "  Commands:"
echo "    npx wrangler logout"
echo "    npx wrangler login"
echo "    # OR"
echo "    export CLOUDFLARE_API_TOKEN='your-token'"
echo ""
echo "Issue 3: Worker code errors"
echo "  Fix: Check worker source code for syntax errors"
echo "  Command: npx wrangler deploy --dry-run --name eastsidebot"
echo ""
echo "Issue 4: Missing dependencies"
echo "  Fix: Ensure all dependencies are installed"
echo "  Command: npm install (or equivalent)"
echo ""
echo "Issue 5: Environment variables missing"
echo "  Fix: Set required secrets/variables"
echo "  Command: npx wrangler secret put VARIABLE_NAME"

# Step 5: Redeployment instructions
echo ""
echo "STEP 5: How to redeploy eastsidebot..."
echo "----------------------------------------"
echo ""
echo "If you have the source code:"
echo "1. cd /path/to/eastsidebot/project"
echo "2. npm install (if package.json exists)"
echo "3. npx wrangler deploy --name eastsidebot"
echo ""
echo "If you DON'T have the source code:"
echo "1. Check Cloudflare dashboard for worker source"
echo "2. Download the worker code from dashboard"
echo "3. Create a new directory and add the code"
echo "4. Deploy with: npx wrangler deploy --name eastsidebot"
echo ""
echo "To update an existing worker:"
echo "npx wrangler deploy --name eastsidebot"

# Step 6: Verification steps
echo ""
echo "STEP 6: Verification steps..."
echo "----------------------------------------"
echo ""
echo "After fixing, verify:"
echo "1. ✅ Worker is deployed: npx wrangler deployments list"
echo "2. ✅ Worker is responding: curl https://eastsidebot.your-subdomain.workers.dev/"
echo "3. ✅ No errors in logs: npx wrangler tail --name eastsidebot"
echo "4. ✅ Check metrics in Cloudflare dashboard"
echo ""
echo "Your dashboard URL:"
echo "https://dash.cloudflare.com/a1ede525e60bbe56f5af3960df6e34c7/workers/services/view/eastsidebot/production/metrics"

# Step 7: Additional help
echo ""
echo "STEP 7: Getting more help..."
echo "----------------------------------------"
echo ""
echo "If you're still having issues:"
echo "1. Check Cloudflare Worker documentation:"
echo "   https://developers.cloudflare.com/workers/"
echo "2. Check wrangler CLI documentation:"
echo "   https://developers.cloudflare.com/workers/wrangler/"
echo "3. Look at worker logs in Cloudflare dashboard"
echo "4. Make sure your account has Workers enabled"
echo ""
echo "========================================="
echo "Fix script complete!"
echo "========================================="