#!/bin/bash
echo "========================================"
echo "GITHUB TOKEN SETUP"
echo "========================================"
echo ""
echo "1. Go to: https://github.com/settings/tokens/new"
echo ""
echo "2. Enter:"
echo "   - Token name: Fork Scraper"
echo "   - Expiration: 7 days (or your choice)"
echo "   - Select scope: ☑️ 'public_repo' (only this one)"
echo ""
echo "3. Click 'Generate token'"
echo ""
echo "4. COPY THE TOKEN (starts with 'ghp_')"
echo ""
echo "5. Paste it here when prompted"
echo ""
read -p "Press Enter to continue..."
