#!/bin/bash
echo "=== Preventing Telegram Bot Conflicts ==="
echo ""
echo "Stopping any Python bots that might conflict with OpenClaw..."
pkill -f "python.*bot\.py"
pkill -f "telegram.*bot"
echo "✅ Killed potential conflicting bots"
echo ""
echo "Current OpenClaw status:"
openclaw gateway status | grep -A1 "Runtime:"
echo ""
echo "To keep only OpenClaw running (recommended):"
echo "1. Don't run any python bot scripts"
echo "2. Use: openclaw gateway restart (if needed)"
echo "3. Test bot: Message @Omamoribotbot on Telegram"
