#!/bin/bash
echo "🔍 Quick UI-TARS Download Check"
echo "================================"
echo ""
echo "Cache size:"
du -sh UI-TARS-1.5-7B/.cache 2>/dev/null || echo "No cache"
echo ""
echo "Model files in main directory:"
ls -1 UI-TARS-1.5-7B/*.safetensors 2>/dev/null | wc -l | xargs echo "Count: "
echo ""
echo "Files found:"
ls -1 UI-TARS-1.5-7B/*.safetensors 2>/dev/null 2>/dev/null || echo "None"
echo ""
echo "Next check in 30 minutes recommended"