#!/bin/bash

echo "=================================================="
echo "Crunchbase Discovery Scraper - Setup Instructions"
echo "=================================================="
echo ""
echo "STEP 1: Check your credentials file"
echo "-----------------------------------"
echo "Current credentials file (.crunchbase_credentials.json):"
cat .crunchbase_credentials.json 2>/dev/null || echo "File not found"
echo ""
echo "STEP 2: Update credentials if needed"
echo "-----------------------------------"
echo "If the email/password are empty or incorrect, update them:"
echo ""
echo "OPTION A: Edit the file manually:"
echo "  nano .crunchbase_credentials.json"
echo ""
echo "OPTION B: Use the Python script:"
echo "  python3 create_credentials.py"
echo ""
echo "The file should look like:"
echo '  {"email": "your_email@example.com", "password": "your_password"}'
echo ""
echo "STEP 3: Run the scraper"
echo "----------------------"
echo "Once credentials are set, run:"
echo "  python3 crunchbase_discovery_scraper.py"
echo ""
echo "This will:"
echo "  1. Open a browser window"
echo "  2. Login to Crunchbase"
echo "  3. Scrape the discovery page"
echo "  4. Save results to JSON and CSV files"
echo ""
echo "Press any key to continue to STEP 3 (run the scraper)..."
read -n 1 -s

echo ""
echo "Starting Crunchbase Discovery Scraper..."
echo "========================================="
python3 crunchbase_discovery_scraper.py